# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: k8s-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Run my-test
        uses: kubeshop/testkube-run-action@v1
        with:
          # Instance
          organization: tkcorg_cd98974363da5c34
          environment: tkcenv_11b64ab6c44a3e65
          token: tkcapi_c07d305e241d4fd04e311c30f02f8f
          # Options
          test: my-test

      # - name: Run test
      #   id: run_test
      #   uses: kubeshop/testkube-docker-action@v1
      #   with:
      #     command: run
      #     resource: test
      #     parameters: my-test
