name: JSON action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-folder:
          - 'sample-test'
          - 'sample-test-2'

    outputs:
      tests: ${{ steps.load_variables.outputs.json }}

    steps:
      # Checks-out only the content of the test folder
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ matrix.test-folder }}
          sparse-checkout-cone-mode: false

      - name: Create JSON definition for testing
        run: |
          if [ ! -f /tmp/foo.txt ]; then
            echo '{"test": []}' | jq . > test.json
          fi
          

      - name: Load testing variables
        id: load_variables
        env:
          EXITING_JSON: ${{ env.sample-test }}
        run: |
          echo $sample-test
          
          echo "Loading JSON variables:"
          json=$(cat ${{ github.workspace }}/${{ matrix.test-folder }}/variables.json)
          
          echo "$(jq '.test += ["${{ matrix.test-folder }}"]' test.json)" > test.json
          
          cat test.json
          json=$(echo $json | jq -r tostring)
          echo "$json"
          
          echo "$(jq '. += {"${{ matrix.test-folder }}":'$json'}' test.json)" > test.json
          
          cat test.json
          
          echo $GITHUB_ENV
           
          # jq -s '.[0] * .[1]' test.json output.json > test.json
          
          json=$(cat test.json)
          
          echo "$json"
          
          echo "json<<EOF" >> $GITHUB_ENV
          echo "$json" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          # echo "json<<EOF" >> $GITHUB_OUTPUT
          # echo "$json" >> $GITHUB_OUTPUT
          # echo "EOF" >> $GITHUB_OUTPUT
          
          echo $GITHUB_ENV

#      - name: Trigger test workflow
#        uses: actions/github-script@v7
#        with:
#          github-token: ${{ secrets.PAT }}
#          script: |
#            github.rest.actions.createWorkflowDispatch({
#              owner: '3KeyCompany',
#              repo: 'Playground',
#              workflow_id: 'reusable-test-action.yml',
#              ref: 'master',
#              inputs: {
#                'test-folder': '${{ matrix.test-folder }}'
#              }
#            })

  reusable-workflow:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Print variables
        run: |
          echo '${{ needs.test.outputs.tests }}'
