name: JSON action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-folder:
          - 'sample-test'

    outputs:
      tests: ${{ steps.load_variables.outputs.sample-test }}
      sample: ${{ steps.load_variables.outputs.sample }}

    steps:
      # Checks-out only the content of the test folder
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ matrix.test-folder }}
          sparse-checkout-cone-mode: false

      - name: Load testing variables
        id: load_variables
        run: |
          echo "Loading JSON variables:"
          cat ${{ github.workspace }}/${{ matrix.test-folder }}/variables.json
          
          # load variables into environment
          while read p; do
            echo "${{ matrix.test-folder }}=$p"
            echo "${{ matrix.test-folder }}=$p" >> "$GITHUB_OUTPUT"
          done < ${{ github.workspace }}/${{ matrix.test-folder }}/variables.json
          
          echo "sample=value" >> "$GITHUB_OUTPUT"

#      - name: Trigger test workflow
#        uses: actions/github-script@v7
#        with:
#          github-token: ${{ secrets.PAT }}
#          script: |
#            github.rest.actions.createWorkflowDispatch({
#              owner: '3KeyCompany',
#              repo: 'Playground',
#              workflow_id: 'reusable-test-action.yml',
#              ref: 'master',
#              inputs: {
#                'test-folder': '${{ matrix.test-folder }}'
#              }
#            })

  reusable-workflow:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Print variables
        run: |
          echo '${{ needs.test.outputs.tests }}'
          echo '${{ needs.test.outputs.sample }}'
