name: Master test action

on:
  workflow_dispatch:

jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        test-folder:
#         - 'sample-test'
#         - 'sample-test2'
#
#    steps:
#      - name: Running the tests
#        run: |
#          echo "Running tests in ${{ matrix.test-folder }}"

  reusable-workflow:
    strategy:
      matrix:
        test-folder:
          - 'sample-test'
          - 'sample-test2'

    uses: 3keycompany/Playground/.github/workflows/reusable-workflow.yml@master
    with:
      test-folder: ${{ matrix.test-folder }}