name: Master test action

on:
  workflow_dispatch:

jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        test-folder:
#         - 'sample-test'
#         - 'sample-test2'
#
#    steps:
#      - name: Running the tests
#        run: |
#          echo "Running tests in ${{ matrix.test-folder }}"
  workflow:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-folder:
          - 'sample-test'
          - 'sample-test2'

    steps:
      # Checks-out only the content of the test folder
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ matrix.test-folder }}
          sparse-checkout-cone-mode: false

      - name: Load testing variables
        id: load_variables
        run: |
          echo "Loading variables:"
          cat ${{ github.workspace }}/${{ matrix.test-folder }}/variables
          
          # load variables into environment
          while read p; do
            echo "$p" >> $GITHUB_ENV
          done < ${{ github.workspace }}/${{ matrix.test-folder }}/variables

      - name: Trigger test workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: '3KeyCompany',
              repo: 'Playground',
              workflow_id: 'reusable-test-action.yml',
              ref: 'master',
              inputs: {
                'test-folder': '${{ matrix.test-folder }}'
              }
            })

#  reusable-workflow:
#    strategy:
#      matrix:
#        test-folder:
#          - 'sample-test'
#          - 'sample-test2'
#
#    env:
#      K8S_CLUSTER: ${{ needs.workflow.outputs.K8S_CLUSTER }}
#
#    uses: 3KeyCompany/Playground/.github/workflows/reusable-test-action.yml@master
#    needs: workflow
#    with:
#      test-folder: ${{ matrix.test-folder }}
#      K8S_CLUSTER: ${{ env.K8S_CLUSTER }}
