name: Master test action

on:
  workflow_dispatch:

jobs:
#  test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        test-folder:
#         - 'sample-test'
#         - 'sample-test2'
#
#    steps:
#      - name: Running the tests
#        run: |
#          echo "Running tests in ${{ matrix.test-folder }}"
  workflow:
    runs-on: ubuntu-latest

    outputs:
      K8S_CLUSTER: ${{ steps.load_variables.outputs.K8S_CLUSTER }}

    strategy:
      matrix:
        test-folder:
          - 'sample-test'
          - 'sample-test2'

    steps:
      # Checks-out only the content of the test folder
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.test-folder }}
          sparse-checkout-cone-mode: false

      - name: Load testing variables
        id: load_variables
        run: |
          echo "Loading variables:"
          cat ${{ github.workspace }}/${{ inputs.test-folder }}/variables
          
          # load variables into environment
          while read p; do
            echo "$p" >> "$GITHUB_OUTPUT"
          done < ${{ github.workspace }}/${{ inputs.test-folder }}/variables

  reusable-workflow:
    strategy:
      matrix:
        test-folder:
          - 'sample-test'
          - 'sample-test2'

    uses: 3KeyCompany/Playground/.github/workflows/reusable-test-action.yml@master
    needs: workflow
    with:
      test-folder: ${{ matrix.test-folder }}
      K8S_CLUSTER: ${{ needs.workflow.outputs.K8S_CLUSTER }}
