name: Test prepare variables

on:
  workflow_call:
    inputs:
      test-folder:
        type: string
        description: 'Test folder to run'
        required: true

run-name: Prepare variables - ${{ inputs.test-folder }}

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      configuration: ${{ steps.load_variables.outputs.configuration }}
    steps:
      # Checks-out only the content of the test folder
      - uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ inputs.test-folder }}
          sparse-checkout-cone-mode: false

      - name: Load testing variables
        id: load_variables
        run: |
          variables_file="${{ github.workspace }}/${{ inputs.test-folder }}/variables.json"
          echo "$(jq '. += {"test-folder":"${{ inputs.test-folder }}"}' $variables_file)" > $variables_file
          echo "Loading JSON variables:"
          json=$(cat $variables_file)
          echo "$json"
          
          echo "configuration<<EOF" >> $GITHUB_OUTPUT
          echo "$json" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  reusable-workflow:
    needs: test
    uses: 3KeyCompany/Playground/.github/workflows/reusable-test-action.yml@master
    with:
      configuration: ${{ needs.test.outputs.configuration }}
    secrets: inherit